// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk_yuRiAwCzBqpBooTvyuanW2unHZzLC4',
    appId: '1:695387301108:web:752bdece0cea67ffe26aa1',
    messagingSenderId: '695387301108',
    projectId: 'medcare-app-2304',
    authDomain: 'medcare-app-2304.firebaseapp.com',
    storageBucket: 'medcare-app-2304.firebasestorage.app',
    measurementId: 'G-LN4ZXQJ4LL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHzdVHGpCeZhmbsB1TM2wk0bdBgYnHJgo',
    appId: '1:695387301108:android:eb8457ad9e58f616e26aa1',
    messagingSenderId: '695387301108',
    projectId: 'medcare-app-2304',
    storageBucket: 'medcare-app-2304.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYljmBmddnQfk-E-7RrbBIEXuokxPZtwo',
    appId: '1:695387301108:ios:4a3d0490bf9794fee26aa1',
    messagingSenderId: '695387301108',
    projectId: 'medcare-app-2304',
    storageBucket: 'medcare-app-2304.firebasestorage.app',
    iosBundleId: 'com.example.medcarePlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYljmBmddnQfk-E-7RrbBIEXuokxPZtwo',
    appId: '1:695387301108:ios:4a3d0490bf9794fee26aa1',
    messagingSenderId: '695387301108',
    projectId: 'medcare-app-2304',
    storageBucket: 'medcare-app-2304.firebasestorage.app',
    iosBundleId: 'com.example.medcarePlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk_yuRiAwCzBqpBooTvyuanW2unHZzLC4',
    appId: '1:695387301108:web:ee04a17ac35a40c0e26aa1',
    messagingSenderId: '695387301108',
    projectId: 'medcare-app-2304',
    authDomain: 'medcare-app-2304.firebaseapp.com',
    storageBucket: 'medcare-app-2304.firebasestorage.app',
    measurementId: 'G-X2BF8M1GB8',
  );
}
